name: "parakeet_tdt_finetune_medical"

trainer:
  devices: 1
  accelerator: gpu
  max_epochs: 30
  log_every_n_steps: 10
  check_val_every_n_epoch: 1
  enable_checkpointing: true
  logger: true
  precision: 16  # AMP/mixed precision

exp_manager:
  exp_dir: ./nemo_experiments/parakeet_tdt_medical
  name: medical_asr_finetune
  create_tensorboard_logger: true
  create_checkpoint_callback: true
  checkpoint_callback_params:
    monitor: val_wer
    mode: min
    save_top_k: 3
    always_save_nemo: true
    save_last: true

model:
  train_ds:
    manifest_filepath: ./data/medical_asr_converted/train_manifest.json
    batch_size: 16
    trim_silence: false
    shuffle: true
    num_workers: 4
    pin_memory: true

  validation_ds:
    manifest_filepath: ./data/medical_asr_converted/val_manifest.json
    batch_size: 16
    trim_silence: false
    shuffle: false
    num_workers: 4
    pin_memory: true

  optim:
    name: adam
    lr: 2.0e-4
    weight_decay: 0.001
    sched:
      name: CosineAnnealing
      warmup_steps: 500
      min_lr: 1.0e-5
