name: "Parakeet-TDT-Finetune-MedicalASR"

# Model config
model:
  sample_rate: 44100
  log_prediction: true
  log_softmax: false
  repeat: 1
  preprocessor:
    _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
    normalize: "per_feature"
    window_size: 0.02
    sample_rate: 44100
    window_stride: 0.01
    window: "hann"
    features: 80
    n_fft: 1024
    frame_splicing: 1
    dither: 1.0e-5
    pad_to: 0
    max_duration: 16.7
  encoder:
    _target_: nemo.collections.asr.modules.ConvASREncoder
    feat_in: 80
    activation: relu
    conv_mask: true
    jasper:
      - filters: 256
        repeat: 1
        kernel: [11]
        stride: [2]
        dilation: [1]
        dropout: 0.2
        residual: false
      - filters: 256
        repeat: 5
        kernel: [11]
        stride: [1]
        dilation: [1]
        dropout: 0.2
        residual: true
  decoder:
    _target_: nemo.collections.asr.modules.ConvASRDecoder
    feat_in: 256
    num_classes: 1024
    vocabulary: null  # will be filled in from tokenizer
  tokenizer:
    dir: null
    type: bpe
    tokenizer_model: null
  loss:
    _target_: nemo.collections.asr.losses.CTCLoss
    zero_infinity: true
  decoding:
    strategy: greedy
    preserve_alignments: false
    compute_timestamps: true

  optim:
    name: adam
    lr: 2.0e-4
    weight_decay: 0.001
    sched:
      name: CosineAnnealing
      warmup_steps: 500
      min_lr: 1.0e-5

# Trainer config
trainer:
  devices: 1
  accelerator: gpu
  max_epochs: 30
  log_every_n_steps: 10
  check_val_every_n_epoch: 1
  logger: true
  enable_checkpointing: true
  precision: 16  # use 16 for mixed precision training

# Dataset config
exp_manager:
  exp_dir: ./nemo_experiments/parakeet_tdt_medical
  name: medical_asr_finetune
  create_tensorboard_logger: true
  create_checkpoint_callback: true
  checkpoint_callback_params:
    monitor: val_wer
    mode: min
    save_top_k: 3
    always_save_nemo: true
    save_last: true

# Paths to manifest files
model.train_ds:
  manifest_filepath: ./data/medical_asr_converted/train_manifest.json
  batch_size: 16
  trim_silence: false
  shuffle: true
  num_workers: 4
  pin_memory: true

model.validation_ds:
  manifest_filepath: ./data/medical_asr_converted/test_manifest.json
  batch_size: 16
  trim_silence: false
  shuffle: false
  num_workers: 4
  pin_memory: true
