name: "parakeet_tdt_finetune_medical"

trainer:
  devices: 1
  accelerator: gpu
  max_epochs: 30
  log_every_n_steps: 10
  check_val_every_n_epoch: 1
  enable_checkpointing: true
  logger: true
  precision: 16  # AMP/mixed precision

exp_manager:
  create_checkpoint_callback: false
  create_tensorboard_logger: false
  create_wandb_logger: false
  create_mlflow_logger: false
  create_dllogger_logger: false


model:
  preprocessor:
    _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
    sample_rate: 44100
    window_size: 0.025        # in seconds (e.g., 25ms)
    window_stride: 0.010      # in seconds (e.g., 10ms)
    window: "hann"
    normalize: "per_feature"
    n_fft: 512
    n_mels: 80
    log: true
    frame_splicing: 1
    dither: 1.0e-5
    pad_to: 16
    pad_value: 0
    mag_power: 2.0
    log_zero_guard_type: clamp
    log_zero_guard_value: 1e-05
    mel_scale: "slaney"


  sample_rate: 44100  # or 16000 if your data is 16kHz
  train_ds:
    manifest_filepath: ./data/medical_asr_converted/train_manifest.json
    batch_size: 16
    sample_rate: 44100  # or 16000 if your data is 16kHz
    trim_silence: false
    shuffle: true
    num_workers: 4
    pin_memory: true

  validation_ds:
    manifest_filepath: ./data/medical_asr_converted/val_manifest.json
    batch_size: 16
    sample_rate: 44100  # or 16000 if your data is 16kHz
    trim_silence: false
    shuffle: false
    num_workers: 4
    pin_memory: true

  optim:
    name: adam
    lr: 2.0e-4
    weight_decay: 0.001
    sched:
      name: CosineAnnealing
      warmup_steps: 500
      min_lr: 1.0e-5
