name: "parakeet_medical_finetune"

model:
  init_from_pretrained_model: ./parakeet-tdt-0.6b-v2
  sample_rate: 16000

  train_ds:
    manifest_filepath: ./data/train.json
    batch_size: 64
    shuffle: true
    is_tarred: false
    use_start_end_token: false

  validation_ds:
    manifest_filepath: ./data/validation.json
    batch_size: 32
    shuffle: false
    is_tarred: false

  preprocessor:
    cls: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
    params:
      normalize: "per_feature"

  optim:
    name: adamw
    lr: 0.001
    weight_decay: 0.01
    sched:
      name: CosineAnnealing
      warmup_steps: 1000

trainer:
  devices: 8
  accelerator: gpu
  strategy: ddp
  precision: 16
  max_epochs: 50
  logger: false

exp_manager:
  exp_dir: ./results/parakeet_medical
  name: nemo_parakeet_medical
  create_tensorboard_logger: true
  create_checkpoint_callback: false
